### ISSUE TITLE
PowervRA Core does not work on CentOS

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#103]
PowervRA Core does not work on Centos. Looks like the issue has already been reported here: https://github.com/PowerShell/PowerShell/issues/2511

Steps to reproduce
------------------

$cred = Get-Credential
 Connect-vRAServer -Server servername -Tenant tenantname -Credential $cred -IgnoreCertRequirements

Expected behaviour
-----------------

A $vRAConnection variable is generated

Actual behaviour
---------------

Invoke-RestMethod : The libcurl library in use (7.29.0) and its SSL backend ("NSS/3.21 Basic ECC") do not support custom handling of
certificates. A libcurl built with OpenSSL is required.
At /root/.local/share/powershell/Modules/PowervRA/Functions/Public/Connect-vRAServer.ps1:134 char:21
+         $Response = Invoke-RestMethod @Params
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-RestMethod], PlatformNotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Environment data
----------------

CentOS 7

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.14
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by Thitho007** [comment]
The problem is not with PowerVRA but with the curl tool in CentOS that does not support OpenSSL.

You can follow the procedure of this site http://www.opentechshed.com/powercli-core-on-centos-7/. This worked well for me with Powershell 6.0.0.17.

Enjoy !

**Comment by chelnak** [comment]
This is cool. Thanks @Thitho007!

**Comment by jonathanmedd** [comment]
The issue was resolved here: https://github.com/PowerShell/PowerShell/issues/2511

Have tested with PS 6.0.0-rc on  centos-release-7-3.1611.el7.centos.x86_64 and all is good :-)
