### ISSUE TITLE
vRA 7.2 support? - Issue with "Get-vRAReservationComputeResource -Type vSphere "

### ISSUE THREAD

**Issue by jturver1** [jakkulabs/PowervRA#110]
Steps to reproduce
------------------
vRA 7.2 environment

Run "Get-vRAReservationComputeResource -Type vSphere ..." using Power-vRA 2 and vRA 7.2

e.g.
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-vRAReservationComputeResource -Type vSphere
Could not find reservation type vSphere
At C:\windows\system32\WindowsPowerShell\v1.0\Modules\PowervRA\Functions\Public\reservation-service\Get-vRAReservationType.ps1:119 char:25
+ ...             throw "Could not find reservation type $($ReservationType ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find reservation type vSphere:String) [], RuntimeException
    + FullyQualifiedErrorId : **Could not find reservation type vSphere**

Expected behavior
-----------------
Returns vRA Compute Resource object ready for viewing or crating new reservations ...

Actual behavior
---------------
Returns error "**Could not find reservation type vSphere**

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value 
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...} 
BuildVersion                   10.0.10586.117 
CLRVersion                     4.0.30319.34014
WSManStackVersion              3.0                                 
PSRemotingProtocolVersion      2.3   
SerializationVersion           1.1.0.1 
----                           -----
PSVersion                      5.0.10586.117  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...} 
BuildVersion                   10.0.10586.117                  
CLRVersion 4.0.30319.34014                                                                                                                                              
WSManStackVersion              3.0                      
PSRemotingProtocolVersion      2.3                                                        
SerializationVersion           1.1.0.1  


> $vRAConnection
PS C:\Windows\System32\WindowsPowerShell\v1.0> $vRAConnection
Server             : https://vra_host
Token              : xxxxxxxxx
Tenant             : vsphere.local
Username           : ldaJustinT@prod.asbgroup.co.nz
APIVersion         : 7.1
SignedCertificates : True
```

**Comment by jturver1** [comment]
Actually, based on this, it looks like the "Name" of the reservation type has changed in vRA 7.2 from "vSphere" to "vSphere (vCenter)":

https://vRA_appliance/reservation-service/api/reservations/types ...
"@type": "ReservationType",
"createdDate": "2016-01-20T09:34:15.068Z",
"lastUpdated": "2017-02-27T01:24:40.319Z",
"version": 5,
"id": "Infrastructure.Reservation.Virtual.vSphere",
"name": "vSphere (vCenter)"
....
... so this works with vRA 7.2:
Get-vRAReservationComputeResource -Type "vSphere (vCenter)" ...

**Comment by jturver1** [comment]
Closing this based on test documented above

**Comment by jonathanmedd** [comment]
Thanks for highlighting this. @chelnak Think we should update the example for this function, or maybe add an extra example for 7.2? Also, is there a way to determine what are the available types?

**Comment by chelnak** [comment]
To view the list of supported resource types for your installation you can use **Get-vRAReservationType**

https://github.com/jakkulabs/PowervRA/blob/development/PowervRA/Functions/Public/reservation-service/Get-vRAReservationType.ps1

I'm sure that this has changed twice now.. originally in v6 it was vSphere (vCenter), then it changed to vSphere and now it appears to have changed back.. maybe I'm wrong.

Thanks for highlighting this @jturver1

**Comment by jonathanmedd** [comment]
OK. I think it might be worth modifying one example to use vSphere (vCenter) and mention that it is needed for say 7.2. Then add an extra example showing how to use Get-vRAReservationType to find a list of types and then select and use one. Maybe something like $type =  Get-vRAReservationType | where {$_.name -match 'vSphere'}; Get-vRAReservationComputeResource -Type $type

**Comment by chelnak** [comment]
Sounds good. Reopening this issue.

**Comment by jturver1** [comment]
FYI - I'd also check that the Get-vRAReservationComputeResource returned object is correctly populated ... just testing earlier it appeared not with 7.2 ...

**Comment by chelnak** [comment]
@jturver1 Out of interest which property was not populated? Was it compopnentId?

**Comment by chelnak** [comment]
closed
