### ISSUE TITLE
xRequires does not work as expected when executed in BEGIN {}

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#124]
The error thrown by xRequires should be terminating. However when the exception is thrown inside a BEGIN block and -ErrorAction is SilentlyContinue the parent function will continue with the function rather than stopping the execution.

## Proposal
Use **Write-Error** and **break** instead of throw. Initial tests are positive and this appears to work for functions that use BEGIN and ones that do not..

```PowerShell
       if ($APIVersion -lt $RequiredVersion) {

            $PSCallStack = Get-PSCallStack

            Write-Error -Message "$($PSCallStack[1].Command) is not supported with vRA API version $($Global:vRAConnection.APIVersion)"
            break

        }
```

**Comment by chelnak** [comment]
Added branch bugfix-xRequires with proposed fix.

Have tested in under the following circumstances
- Inside begin block
- Inside begin  block with EA = SilentlyContinue
- Inside try/catch
- Inside try/catch with EA = SilentlyContinue
- outside try/catch
- outside try/catch with EA = SilentlyContinue

@jonathanmedd  can you test when you get back?

Thanks

**Comment by jonathanmedd** [comment]
I tested it with Get-vRAIcon and 6.2 with xRequires in the Begin block, seems to work as expected without your suggestion. Let's catchup on this one

**Comment by chelnak** [comment]
No probs - updated the description a little too
