### ISSUE TITLE
Request-vRACatalogItem Argument "-Confirm" not implemented 

### ISSUE THREAD

**Issue by Thitho007** [jakkulabs/PowervRA#138]
Firstly, Thanks for your project and your effort.
I use your project in a script. And I have a problem with the arg -Confirm in your cmdlet Request-vRACatalogItem. The Get-Help report that the Arg exists and I don't find it the your cmdlet :'(

Would be cool to have a way to send a request in non-interactive mode.
Thx
FYI : I'm on a Linux Box (CentOS)

Steps to reproduce
------------------
```powershell
Request-vRACatalogItem -JSON $JSON_STRING -Wait -Confirm $false
```

Expected behavior
-----------------
No Prompt to user

Actual behavior
---------------
```powershell
Request-vRACatalogItem -JSON $JSON_STRING -Wait -Confirm $false
Request-vRACatalogItem : A positional parameter cannot be found that accepts argument 'False'.
At line:1 char:1
+ Request-vRACatalogItem -JSON $JSON_STRING -Wait -Confirm $false
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Request-vRACatalogItem], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Request-vRACatalogItem
```
Environment data
----------------

```powershell
>  
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.18
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
> 
```powershell
$vRAConnection


Server             : https://myhost.vra.com
Token              : ****************************
                     
Tenant             : vsphere.local
Username           : VRAUSER
APIVersion         : 7.1
SignedCertificates : True
```
>
```powershell
Get-vRAVersion


BuildNumber        : 4659752
BuildDate          : 2016-11-16 23:16
ProductVersion     : 7.2.0-SNAPSHOT
APIVersion         : 7.1
ProductBuildNumber : 7.2.0-SNAPSHOT-4659752
```

**Comment by chelnak** [comment]
Hi!

One of us will check this out ASAP for you. 

In the meantime can you try this syntax for the Confirm parameter.

```
-Confirm:$false
```

Thanks!

**Comment by jonathanmedd** [comment]
`-confirm:$false`

is the correct way to address that parameter. Switch parameters are either present or not, consequently the $false in the example is attempting to bind to one of the earlier parameters specified.

Binding to a switch parameter, such as `-confirm` requires the colon.

So I think we can close this issue.

**Comment by Thitho007** [comment]
Hello,

Oh my mistake (Linux user here ;-) and newbie on Powershell )...
I confirm that is works !

Thanks

**Comment by Thitho007** [comment]
Hello,

Oh my mistake (Linux user here ;-) and newbie on Powershell )...
I confirm that is works !

Thanks

**Comment by jonathanmedd** [comment]
That's cool. I don't think it is the most obvious syntax to someone not familiar with PowerShell.

Thanks for your interest in PowervRA!
