### ISSUE TITLE
Implement New-vRAUserPrincipal

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#14]
Implement New-vRAUserPrincipal so that local horizon users can be created for a tenant:

```
/identity/api/docs/resource_Principal.html#POST
```

Also see Get-vRAUserPrincipal for reference

**Comment by destroy-everything** [comment]
see PR #36

**Comment by chelnak** [comment]
@destroy-everything Great stuff thank you for this! Will review and merge PR #36 ASAP. :+1:

**Comment by chelnak** [comment]
@destroy-everything What is your twitter handle?

**Comment by destroy-everything** [comment]
This is the closest thing to social media I get to

**Comment by chelnak** [comment]
No worries :-)
