### ISSUE TITLE
Using PowervRA and vRO does not work for Request-vRACatalogItem 

### ISSUE THREAD

**Issue by debian00001** [jakkulabs/PowervRA#140]
Hello,

I am using the PowervRA module and I can't seem to run the command bekow after conencting

Request-vRACatalogItem -JSON $DatacenterFile -Confirm:$false

[2017-05-11 15:35:08.156] [E] (com.vmware.library.powershell/invokeScript) Error in (Dynamic Script Module name : invokeScript#14) PowerShellInvocationError: Errors found while executing script 
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()

What is strange is a command like this gets the expected output in vRO.

Get-vRABlueprint 

Any ideas? Please note, I can run the .ps1 script I created all the time to make it work. The problem is trying to make it work with vRealize Orchestrator is where I get the error above...

**Comment by chelnak** [comment]
Hey! Could you provide us some diagnostic information?

* PowerShell Version Information - $PSVersionTable
* vRA Connection info - $vRAConnection
* Your vRO Version

A 400 error usually means that the data being send is somehow incorrect.

Have you validated the contents of $DatacenterFile in vRO?

**Comment by debian00001** [comment]
Hello!

PowerShell version.

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

vRA Connection Info

Server             : https://cloud.domain.com
Token              : MTQ5NDUzNzA4NzQ4NDoyNTIwNWNiZjViZjMzNTlmMDllYzp0ZW5hbnQ6dnNwaGVyZS5sb2NhbHVzZXJuYW1lOm1tYWRlamFAaW
                     FhaS5jb21leHBpcmF0aW9uOjE0OTQ1NjU4ODcwMDA6ZWVkMjAzYjc2MzE1MzVhZTVkN2QzZmQxNGYzYWJlODUyZmFhMWRiNzA0
                     OWMwZGU4YWIyMmU5M2EwNTUzNTNlYzU2Y2M4NjZlODUyNzBiZDU0M2U2ZjI3ZGU5NDg1ODc0OTdkMDM5MDA3MTViYjVmNzU0ZD
                     YwMTA0N2VhYzQzY2E=
Tenant             : vsphere.local
Username           : me@user.com
APIVersion         : 7.1
SignedCertificates : False

vRO is 7.2

I have validated that the PowerShell script that has PowerVRA components works on it's own. When I run it in vRO, it bombs with that 400 error... I will review again but since it works fine on it's own and I have the same data in vRO, I'm at a loss...

**Comment by jonathanmedd** [comment]
Are you able to log the contents of $DatacenterFile in vRO to see if there are any differences than when running it from an interactive PowerShell session?

**Comment by debian00001** [comment]
Disregard, this can be closed. It seems the output had something wrong with it for the JSON file I was manipulating. Thanks for the prompt response!

This solution is awesome and is exactly what I need to make a single pane of glass!

**Comment by jonathanmedd** [comment]
OK, thanks for letting us know.

Also, thanks for the kind feedback - it's always nice to hear :-)
