### ISSUE TITLE
Pull Configurations from PowerVRA

### ISSUE THREAD

**Issue by mikemadeja** [jakkulabs/PowervRA#143]
Hello,

Is it possible to pull in Configurations from PowerVRA?

If you click Design, then the paper with the cog in it, I was hoping I can pull data from that.. is it possible?

![image](https://user-images.githubusercontent.com/28938328/29367391-574e02e4-8262-11e7-8697-026e561e88d7.png)

**Comment by chelnak** [comment]
Hey @mikemadeja  - you might want to check out PowervRO for this:

https://github.com/jakkulabs/PowervRO

Specifically these functions:
http://powervro.readthedocs.io/en/latest/Export-vROConfigurationElement/
http://powervro.readthedocs.io/en/latest/Get-vROConfigurationElement/
