### ISSUE TITLE
Support for vRA 7.2/7.3?

### ISSUE THREAD

**Issue by jturver1** [jakkulabs/PowervRA#145]
Steps to reproduce
------------------
No support with vRA 7.2 or 7.3?

Expected behavior
-----------------
Are there any updates on the way that will provide support for vRA 7.2 / 7.3?

Actual behavior
---------------

Environment data
----------------

```powershell
> $PSVersionTable

> $vRAConnection

```

**Comment by chelnak** [comment]
Hey @jturver1 ,

PowervRA should support 7.2.

As for 7.3 no formal tests have been done at the moment. However I would imagine the majority of the existing functionality works.

Is there anything you are looking for in particular or have you found something that is not functioning as expected?

Thanks

**Comment by skunkie** [comment]
In 7.3 I found that the name for reservation type is changed from 'vSphere' to 'vSphere (vCenter)', so I made this change in New-vRAReservation.ps1 to make it work:
```diff
@@ -333,7 +333,7 @@
 
                     switch ($PSBoundParameters.Type) {
 
-                        'vSphere' {
+                        'vSphere (vCenter)' {
                             
                             # ---
                             # --- Alert Policy

**Comment by jonathanmedd** [comment]
@skunkie Thanks for reporting the problem. Have created an issue for it here: https://github.com/jakkulabs/PowervRA/issues/149

**Comment by jonathanmedd** [comment]
For info, have resolved the issue #149 mentioned above. Will target release v2.2.2 for full testing of vRA 7.2 and 7.3

**Comment by jonathanmedd** [comment]
Have tested vRA 7.2 - all good. 7.3 tests to follow.

**Comment by jonathanmedd** [comment]
Have tested vRA 7.3 - all good.
