### ISSUE TITLE
Request-vRAResourceAction Example Correction

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#148]
This example for Request-vRAResourceAction does not work:

$ResourceActionId = (Get-vRAResource -Name vm01 | Get-vRAResourceAction "Reboot").id

I think it should be corrected to:

$ResourceActionId = (Get-vRAResource -Name vm01 | Get-vRAResourceAction | Where-Object {$_.Name -eq "Reboot"}).id

**Comment by chelnak** [comment]
Fixed - thanks for pointing out @jonathanmedd
