### ISSUE TITLE
Support Reservation Type change from 'vSphere' to 'vSphere (vCenter)' in vRA 7.3

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#149]
Steps to reproduce
------------------

Run New-vRAReservation to create a new reservation

Expected behavior
-----------------

Creates a reservation

Actual behavior
---------------

Fails because the type has changed from 'vSphere' to 'vSphere (vCenter)'  

Environment data
----------------

vRA 7.3

Making the following code change as a temporary workaround resolves the issue

                     switch ($PSBoundParameters.Type) {
 
                        'vSphere' {
                        'vSphere (vCenter)' {
                             
                             # ---
                             # --- Alert Policy`

More details can be found here: https://github.com/jakkulabs/PowervRA/issues/145#issuecomment-332675531

**Comment by jonathanmedd** [comment]
The other Reservation functions also need to be tested for the same issue

**Comment by vinithmenon28** [comment]
Hello Team,

Even the below command needs an update for vRA 7.3.

PS C:\WINDOWS\system32> gcm *Get-vRAReservationCompute*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-vRAReservationComputeResource                  2.2.0      PowerVRA
Function        Get-vRAReservationComputeResourceMemory            2.2.0      PowerVRA
Function        Get-vRAReservationComputeResourceNetwork           2.2.0      PowerVRA
Function        Get-vRAReservationComputeResourceResourcePool      2.2.0      PowerVRA
Function        Get-vRAReservationComputeResourceStorage           2.2.0      PowerVRA

PS C:\WINDOWS\system32> Get-vRAReservationComputeResourceNetwork -Type vSphere -ComputeResourceId 8f967292-6d15-47bd-b7eb-a8400bcf3571
Could not find reservation type vSphere
At C:\Program Files\WindowsPowerShell\Modules\PowerVRA\2.2.0\Functions\Public\reservation-service\Get-vRAReservationType.ps1:119 char:25
+ ...             throw "Could not find reservation type $($ReservationType ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find reservation type vSphere:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find reservation type vSphere

**Comment by jonathanmedd** [comment]
Thanks for that. We'll address that in this bug too

**Comment by jonathanmedd** [comment]
For our own reference this applies to both 7.2 and 7.3

**7.1:**
```
Get-vRAReservationType | ft Id,Name -AutoSize

Id                                           Name           
--                                           ----           
Infrastructure.Reservation.Cloud.Amazon      Amazon         
Infrastructure.Reservation.Virtual.HyperV    Hyper-V        
Infrastructure.Reservation.Virtual.KVM       KVM            
Infrastructure.Reservation.Cloud.OpenStack   OpenStack      
Infrastructure.Reservation.Virtual.SCVMM     SCVMM          
Infrastructure.Reservation.Cloud.vCloudAir   vCloud Air     
Infrastructure.Reservation.Cloud.vCloud      vCloud Director
Infrastructure.Reservation.Virtual.vSphere   vSphere        
Infrastructure.Reservation.Virtual.XenServer XenServer 
```

**7.2:**
```
Get-vRAReservationType | FT ID,Name -AutoSize

Id                                           Name                
--                                           ----                
Infrastructure.Reservation.Cloud.Amazon      Amazon EC2          
reservation.type.id.azure                    Azure               
Infrastructure.Reservation.Virtual.SCVMM     Hyper-V (SCVMM)     
Infrastructure.Reservation.Virtual.HyperV    Hyper-V (Standalone)
Infrastructure.Reservation.Virtual.KVM       KVM (RHEV)          
Infrastructure.Reservation.Cloud.OpenStack   OpenStack           
Infrastructure.Reservation.Cloud.vCloudAir   vCloud Air          
Infrastructure.Reservation.Cloud.vCloud      vCloud Director     
Infrastructure.Reservation.Virtual.vSphere   vSphere (vCenter)   
Infrastructure.Reservation.Virtual.XenServer XenServer    
```
**7.3:**
```
Get-vRAReservationType | ft ID,Name

Id                                           Name
--                                           ----
Infrastructure.Reservation.Cloud.Amazon      Amazon EC2
reservation.type.id.azure                    Azure
Infrastructure.Reservation.Virtual.SCVMM     Hyper-V (SCVMM)
Infrastructure.Reservation.Virtual.HyperV    Hyper-V (Standalone)
Infrastructure.Reservation.Virtual.KVM       KVM (RHEV)
Infrastructure.Reservation.Cloud.OpenStack   OpenStack
Infrastructure.Reservation.Cloud.vCloudAir   vCloud Air
Infrastructure.Reservation.Cloud.vCloud      vCloud Director
Infrastructure.Reservation.Virtual.vSphere   vSphere (vCenter)
Infrastructure.Reservation.Virtual.XenServer XenServer

```
