### ISSUE TITLE
Set-vRAReservationNetwork doesn't support Security Groups

### ISSUE THREAD

**Issue by blackms** [jakkulabs/PowervRA#161]
Hello, That command doesn't support Security Groups. Is it correct?

**Comment by jonathanmedd** [comment]
@blackms Correct, it supports Network Path and Network Profile.

Not quite sure how you would use a Security Group (I presume you mean NSX?) in a Reservation. Perhaps you could elaborate further?

**Comment by blackms** [comment]
Yes, once you define Security Groups in NSX you can map them on Reservations. I will try to make a PR in the following days so the feature will be supported.

**Comment by jonathanmedd** [comment]
Sounds great. Look forward to seeing it

**Comment by jonathanmedd** [comment]
Have updated a few of the tags which help us keep on top of these issues. No pressure on us to meet the 3.1 milestone (we don't even have a date for it) - it's just so we know what we might be including.
