### ISSUE TITLE
Enhancement: Implement $IsCoreCLR

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#162]
@jonathanmedd 

In PowerShell Core there is a variable $IsCoreCLR, which tells us that we are using core.

It could be cleaner to use this variable and rather than things like this:

```if ($PSVersionTable.PSEdition -eq "Desktop" -or !$PSVersionTable.PSEdition) {```

We could do:

```if(!$IsCoreCLR)``` or ```if($IsCoreCLR)```

**Comment by jonathanmedd** [comment]
Closed via PR #164
