### ISSUE TITLE
cmdlet for catching request result by invoking /catalog-service/api/consumer/requests/<id>/forms/details

### ISSUE THREAD

**Issue by otabut** [jakkulabs/PowervRA#165]
Hi,

I might be wrong but I can't find a cmdlet for catching up the result of a completed request. The closest one is Get-vRARequest but it allows only to retrieve the completion status, not the data that may be returned by the request itself.

This can be done by invoking the following url :  /catalog-service/api/consumer/requests/<id>/forms/details

Thanks for your answer and sorry if there was an obvious answer I was not able to find.

Regards.

**Comment by jonathanmedd** [comment]
You are correct, that is currently not available, but we can add it as a feature request to make a Get-vRARequestDetail function.

You are welcome to submit a PR for it ;-)

**Comment by jonathanmedd** [comment]
Closed via this PR: https://github.com/jakkulabs/PowervRA/pull/167
