### ISSUE TITLE
Release 3.0.0.8 zip file only doesn't contain Functions directory

### ISSUE THREAD

**Issue by Thitho007** [jakkulabs/PowervRA#170]
Steps to reproduce
------------------
Get https://github.com/jakkulabs/PowervRA/releases/download/v3.0.0-8/PowervRA.3.0.0-8.zip
Extract the content of archive

Expected behavior
-----------------
Get all files & Functions directory

Actual behavior
---------------
Retrieves only 2 files (PowervRA.psd1 & PowervRA.psm1)

Environment data
----------------

```powershell
> $PSVersionTable
N/A

> $vRAConnection
N/A
```

**Comment by jonathanmedd** [comment]
It's our new build process for a release. Although we still develop the functions in separate directories, during the build for a release we combine all the functions into a single PSM1 file for performance reasons.

We added this line to the release notes for 3.0.0:

Feature - Single PSM1 file to speed up load times

**Comment by Thitho007** [comment]
OK I see.

Sorry my bad...

**Comment by jonathanmedd** [comment]
No problem, thanks for the interest in the project.
