### ISSUE TITLE
get-vrapackage results in "Package with conent [caebc2ac-60b4-4813-981d-507b28e0e709] not found. Please remove it from your package and retry your operation."

### ISSUE THREAD

**Issue by jzajac2** [jakkulabs/PowervRA#176]
Steps to reproduce
------------------
1. connect to server
2. run `Get-vRAPackage`
`Result:  {"errors":[{"code":85552,"message":"Package with content [caebc2ac-60b4-4813-981d-507b28e0e709] not found. Please remove it from your package and retry your operation.","systemMessage":"85552-Package with content [caebc2ac-60b4-4813-981d-507b28e0e709] not found. Please remove it from your package and retry your operation.","moreInfoUrl":null}]}`

running: `$test = Get-vRAPackage -Id "cc7500d9-3e23-4a87-9fd9-aec3df0c86bd"`
results in nothing.` $test.GetType()` for example: `[ERROR] You cannot call a method on a null-valued expression.`

Expected behavior
-----------------
Return all the packages. Well..requesting guidance here, for example, how to dig into the specific corrupted package so I can dig.

Actual behavior
---------------
`{"errors":[{"code":85552,"message":"Package with content [caebc2ac-60b4-4813-981d-507b28e0e709] not found. Please remove it from your package and retry your operation.","systemMessage":"85552-Package with content [caebc2ac-60b4-4813-981d-507b28e0e709] not found. Please remove it from your package and retry your operation.","moreInfoUrl":null}]}`

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value                                                                                                                      
----                           -----                                                                                                                      
PSVersion                      5.1.14409.1012                                                                                                             
PSEdition                      Desktop                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                    
BuildVersion                   10.0.14409.1012                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                            
WSManStackVersion              3.0                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                        
SerializationVersion           1.1.0.1   
> $vRAConnection
Server             : wontshare
Token              : wontshare
                     
Tenant             : wontshare
Username           : wontshare
APIVersion         : 7.1
SignedCertificates : False
SslProtocol        : Default
```

**Comment by jonathanmedd** [comment]
So it sounds like the content item with id 'caebc2ac-60b4-4813-981d-507b28e0e709' has been removed, while the package with id "cc7500d9-3e23-4a87-9fd9-aec3df0c86bd" still exists?

The error from the API doesn't seem to contain the id of the affected package, so how did you know that it was the package with id "cc7500d9-3e23-4a87-9fd9-aec3df0c86bd"?

If you're sure that is the right one, maybe try Remove-vRAPackage to get rid of it. Although I suspect since Get-vRAPackage does not return any result, this may not work.

**Comment by jzajac2** [comment]
Error has "gone away". Too many cooks in the kitchen at that time I guess. Thanks for the feedback I'm sure this will come up again and if so I'll dig and update in case this happens to someone else
