### ISSUE TITLE
Is there a way to get representation (json?) of a submitted request?

### ISSUE THREAD

**Issue by jzajac2** [jakkulabs/PowervRA#177]
This not a bug :). More of a question, possible enhancement request if you do that sort of thing.

My end goal is to be able to run test requests - end-to-end type testing. I figured I could do this by `Get-vRACatalogItemRequestTemplate` , modifying required the json values in memory, then saving it back to disk (maybe I won't need to save to disk actually, however this is working for me so far) then (pseudocode, not sure I can pipe this way) `get-content $myTemplatePathOnDisk -Raw | Request-vRACatalogItem -JSON`.  

However running into issues on which json values I need to modify and _how_ to modify them (seems to be a form value -> shortname value mapping going on here). So I figured if I could submit some requests manually through the Catalog service portal and if successful, get that request's json string, I can see how I need to construct the values in my automated requests. There doesn't seem to be a wrapping cmdlet in PowervRA, or is there? If not, would this be possible through the `Invoke-vRARestMethod`? And if so and it's at the top of your head would you mind sharing?

Basically, I'm getting this error: 

> {"errors":[{"code":20117,"message":"The data specified within the request is invalid.","systemMessage":"The data specified within the request is invalid.","moreInfoUrl":null},{"code":10100,"message":"Composite error.","systemMessage":"Composite Exception.","moreInfoUrl":null}]}
At C:\Program Files\WindowsPowerShell\Modules\PowervRA\3.0.0\PowervRA.psm1:748 char:13
\+             Invoke-RestMethod @Params
\+             ~~~~~~~~~~~~~~~~~~~~~~~~~
\+ CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    \+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

however it's tough to tell exactly which part of the data is bad, hence I'd like to see a representation of a good/working one

**Comment by chelnak** [comment]
Try running Request-vRACatalogItem with the -Debug switch. It potentially
does what you need.

**Comment by jzajac2** [comment]
Using the -Debug switch (powershell common parameter) yes, outputs my json body, however something might be wrong with my json body and that's what I'm trying to figure out. I'm trying to figure that out by seeing the json of a successful request.

Looks like I can get this by: `catalog-service/api/consumer/requests/{myRequestId}` ?
Just tried via postman and it seemed to work (however not formatted the way I'd like in order to get a clean diff).

Not sure if this is due to my bad json input, but the lower level error is:

> At line:1 char:1
\+ @Params
\+ ~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@Params' can be used only as an argument to a command. To reference variables in an expression use '$Params'.

See image attached. My call which led me to this error (again, valid JSON but probably not correct per our vra system requirements/setup) was this: `Request-vRACatalogItem -Debug -JSON $jsonStrRequest`

See screenshot:
![image](https://user-images.githubusercontent.com/101703/37675126-742c2dc0-2c42-11e8-884b-7376fc9b8d28.png)

**Comment by jonathanmedd** [comment]
Take a look at Get-vRARequest and Get-vRARequestDetail, they might do what you are looking for.

They are using `catalog-service/api/consumer/requests/{myRequestId}`

See also issue #165
