### ISSUE TITLE
case sensitivity 

### ISSUE THREAD

**Issue by 010101010100** [jakkulabs/PowervRA#186]
Hi,
Working through a project where I wanted to get setting from one vra system and set those same setting on a new vra (prod / dev environments). Simplified to something like:

`Get-vRATenant | ConvertTo-Json | New-vRATenant`

The problem encountered is the custom object key names do not match the expected json case so the above pipe fails. 

In Get-vRATenant this is define as:

```
            [pscustomobject]@{

                Id = $Response.id
                UrlName = $Response.urlName
                Name = $Response.name
                Description = $Response.description
                ContactEmail = $Response.contactEmail
                Password = $Response.password
                DefaultTenant = $Response.defaultTenant
            }
```

Expected is the first char lowercase:
```
    {
      "name" : "Tenant02",
      "description" : "This is Tenant02",
      "urlName" : "Tenant02",
      "contactEmail" : "test.user@tenant02.local",
      "id" : "Tenant02",
      "defaultTenant" : false,
      "password" : ""
    }
```

Is there perhaps another way to do this?
Regards

**Comment by jonathanmedd** [comment]
I'm guessing this is some kind of two step process, like you are exporting the config to JSON then later on using that exported data to create the same thing in another vRA system?

If so, can you not just convert the JSON data back to a PowerShell object from the exported data, e.g.

```
$json = Get-vRATenant | ConvertTo-Json
```

is you initial export. Then something like the following on the new system:

```
$data = $json | ConvertFrom-Json
New-vRATenant -Name $data.name -Description $data.description -URLName $data.urlName -ContactEmail $data.contactEmail -ID $data.id
```

**Comment by 010101010100** [comment]
Yes, exactly that two step process and I am currently using the option you provided to feed the data with the named parameters. 

This could be simplified though if the keys defined in Get-vRA* pscustomobject used the same case vra expects. This could then be piped as proper json, saved as backup for later replay etc. I tested a few by just changing the first char from upper to lower and it worked no prob. The json structure is already there. 

BTW, The pipeline is super useful and much thanks for the time and effort creating this project!

**Comment by jonathanmedd** [comment]
OK. @chelnak and I have discussed this and we are not going to update the case of the output, since we would then need to do that across the whole project in order to remain consistent. Whether it's a good thing or not, the typical output from PowerShell cmdlets is not in lower case, so we wish to stay consistent against that.

For your particular scenario you could do something using calculated properties to have the property names in the format you need, like the following:

```
Get-vRATenant | select @{N='id';E={$_.Id}},@{N='urlName';E={$_.UrlName}},@{N='name';E={$_.Name}},@{N='description';E={$_.Description}},@{N='contactEmail';E={$_.ContactEmail}},@{N='password';E={$_.Password}},@{N='defaultTenant';E={$_.DefaultTenant}}
```

It's pretty ugly, but I believe would do what you want it to do. Hope this helps

**Comment by 010101010100** [comment]
Thank you for considering this change and providing alternative approaches.
