### ISSUE TITLE
Set-vRAReservation not working correct for Type 'vSphere (vCenter)'

### ISSUE THREAD

**Issue by azbpa** [jakkulabs/PowervRA#188]
The function `Set-vRAReservation` is not working correct for `vSphere (vCenter)` reservations in vRA 7.4.

Reason is probably the `Switch` statement here:
https://github.com/jakkulabs/PowervRA/blob/v3.3.0/src/Functions/Public/reservation-service/Set-vRAReservation.ps1#L270

It is only defined for type `vSphere` but not for `vSphere (vCenter)`.

Steps to reproduce
------------------
In example while trying to change the `Quota` of an `vSphere (vCenter)` reservation.

```
Get-vRAReservation -Name "Test_vSphere_Reservation" | Set-vRAReservation -Quota 1
```

Expected behavior
-----------------
Quota will be set to `1`

Actual behavior
---------------
Quota will have the same value as before.

Environment data
----------------

vRA 7.4

**Comment by jonathanmedd** [comment]
@azbpa Thanks for raising this. It's the same problem as issue #149 , but we missed Set-vRAReservation in the functions that were fixed.
