### ISSUE TITLE
error code 90135 Unable to authenticate user <domain>\\<username> in tenant <tenant>

### ISSUE THREAD

**Issue by aenagy** [jakkulabs/PowervRA#189]
Steps to reproduce
------------------
(1) Install-Module -Name PowervRA -Scope CurrentUser
(2) Connect-vRAServer -Server (FQDN of vRA) -Tenant (tenant) -Credential (Get-Credential) -IgnoreCertRequirements

Expected behavior
-----------------
Connect to vRA named tenant using Active Directory credentials.

Actual behavior
---------------
Invoke-RestMethod : {"errors":[{"code":90135,"source":null,"message":"Unable to authenticate user (domain)\\(tenant) in tenant (tenant).","systemMessage":"90135-Unable to authenticate user (domain)\\(tenant) in tenant (tenant).","moreInfoUrl":null}]}
At (folder path to user's profile)\OneDrive - (my corp)\Documents\WindowsPowerShell\Modules\PowervRA\3.3.0\PowervRA.psm1:501 char:21
+         $Response = Invoke-RestMethod @Params
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.666
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.666
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> $vRAConnection
(no output)
```

**Comment by jonathanmedd** [comment]
@aenagy Interesting. I can reproduce this if I enter my credentials in the format:
```
DOMAIN\username
```
like you appear to have done.

Can you try it with:

```
username@domain
```

**Comment by jonathanmedd** [comment]
From testing, it would appear that the vRA REST API may not support usernames in the format ```Domain\username```.

Have posted this to find out more: https://communities.vmware.com/message/2825482#2825482

Depending on the response, may just update the code to convert a ```Domain\username``` into a ```username@domain``` type.

**Comment by jonathanmedd** [comment]
The response to this post  https://communities.vmware.com/message/2825482#2825482 was the the username format Domain\Username is not supported by the REST API.

Consequently I have updated the code with better help info and set Connect-vRAServer to throw if the username is in that format.
