### ISSUE TITLE
Compatiblity Question

### ISSUE THREAD

**Issue by Stephanevg** [jakkulabs/PowervRA#199]
Hi, I just have a question regarding Compatability.

Up until which version is this module compatible. On the Readme page is states 7.3, but today there is vRA 7.4 and 7.5. 

Is the readme simply not up to date, or is it really not compatible with these versions?

Cheers

**Comment by kclinden** [comment]
I have been using this with vRA 7.4 with no issues. I have probably only used about 10 of the cmdlets though.

**Comment by jonathanmedd** [comment]
Unfortunately we don't have the resource available to fully test everything every time a new vRA version is released.

The readme will show what we have been able to test against. If you experience a problem with a later vRA version then best thing to do is raise an issue here for us to investigate.
