### ISSUE TITLE
Get-vRABusinessGroup TenantId Parameter

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#2]
After talking the other week I understand why this is important. But maybe it should take the value of the current tenant for a default value. I always think of business groups being managed from within the current tenant.
Also I rememer that tenantid is case sensitive, Would it be worth doing a get-vRATenant to ensure that the TenantId is correct.
I do something similar in New-vRAEntitlement:

 Ensure the correct tenant name is used in Get-vRABusinessGroup
$TenantName = (Get-vRATenant $Global:vRAConnection.Tenant).Id

**Comment by jonathanmedd** [comment]
@chelnak Can you check what's in the commit is what you were looking for with this? Thanks

**Comment by chelnak** [comment]
@jonathanmedd  Looks cool - made some comments on the commit

Could you check out the new version of Connect-vRAServer in the feature branch and let me know if you are happy with it?

If you are I will submit a pull request and get it merged in to development

**Comment by jonathanmedd** [comment]
Thanks for the feedback. Have updated accordingly :-)

And yes, I tested it against the version of Connect-vRAServer you mentioned. Happy for you to merge the stuff in there
