### ISSUE TITLE
[Question] Trigger snapshots on VM's

### ISSUE THREAD

**Issue by Stephanevg** [jakkulabs/PowervRA#208]
Hi

I was wondering if it is possible to trigger snapshots using this module?
I search in the documentation [here](https://powervra.readthedocs.io/en/latest/search.html?q=snapshot) but I couldn't find anything.

If it is not possible, any idea where to start?

Thanks in advance

**Comment by kclinden** [comment]
To accomplish this you will want to use the ResourceAction cmdlets. 

https://powervra.readthedocs.io/en/latest/functions/Request-vRAResourceAction/

High level steps to accomplish this are:

1. Get-vRAResource | select Name, ResourceId
2. Get-vRAResourceAction -ResourceId $resourceId
3. Request-vRAResourceAction -ResourceId $resourceId -ActionId $actionId

Depending on the action you may have to get a request template.  To accomplish this you will want to use the ResourceAction cmdlets. 

https://powervra.readthedocs.io/en/latest/functions/Request-vRAResourceAction/

High level steps to accomplish this are:

1. Get-vRAResource | select Name, ResourceId
2. Get-vRAResourceAction -ResourceId $resourceId
3. Request-vRAResourceAction -ResourceId $resourceId -ActionId $actionId

Depending on the action you may have to get a request template.
