### ISSUE TITLE
-Wait:false still waits

### ISSUE THREAD

**Issue by shorbachuk** [jakkulabs/PowervRA#210]
Steps to reproduce
------------------
When Request-vRACatalogItem -Wait:$false or Get-vRAResourceOperation -Wait:$false is invoked. The cmdlet still waits.

Instead of 

if ($PSBoundParameters.ContainsKey("Wait"))

I believe it should be

if($Wait)

Expected behavior
-----------------
No waiting

Actual behavior
---------------
Waits

Environment data
----------------
Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by chelnak** [comment]
The param type is [switch] so $Wait.IsPresent is probably the way to go here.

Going from what you’ve said I’m assuming you are running the command in some sort of script with different code paths?

**Comment by shorbachuk** [comment]
Yes, I am running inside another script and I’d like to pass the parameter threw. Currently I am working around it like this:

If($NeedsWait) {
  Request-vRACatalogItem -Wait
}
Else {
  Request-vRACatalogItem 
}

Request-vRACatalogItem -Wait:$NeedsWait would be a lot cleaner

**Comment by jonathanmedd** [comment]
Thanks for reporting and solving it for us. PR #212
