### ISSUE TITLE
Stop waiting on REJECTED state

### ISSUE THREAD

**Issue by shorbachuk** [jakkulabs/PowervRA#211]
Steps to reproduce
------------------
Request-vRACatalogItem -Wait

Expected behavior
-----------------
Stops waiting in the case the request is REJECTED. In my case, the request is rejected automatically by an approval policy. 

Actual behavior
---------------
Cmdlet continues to wait, indefinitely. 

Environment data
----------------

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by jonathanmedd** [comment]
Thanks for reporting and solving it for us.
