### ISSUE TITLE
Secure VRAConnect

### ISSUE THREAD

**Issue by martin9700** [jakkulabs/PowervRA#227]
Steps to reproduce
------------------
$Global:vraconnection
`Server             : https://server.domain.local
Token              : <token>
RefreshToken       : <refreshtoken>
APIVersion         : 2019-01-15
SignedCertificates : False
SslProtocol        : Default`

Expected behavior
-----------------
$Global:vraconnection
<null>

Also: $Script:vraconnection
<null>

**Comment by Stevio54** [comment]
could you detail out the issue please?

**Comment by martin9700** [comment]
Sure, when you Connect-VraServer, you can simply type $Global:VraConnection and see both tokens required for accessing VRA.  It would certainly be possible for someone to walk up , get those tokens then start doing work AS YOU.  Attack surface area is pretty low, but it's simple to fix so why not?

I can submit a PR if you'd like?

**Comment by Stevio54** [comment]
Thanks for clarifying the issue. Would it be possible for you to submit a PR?

**Comment by jonathanmedd** [comment]
Thanks for this! I didn't realise until today that “script scope in a module is module scope” otherwise we would have done this from the beginning :-)

**Comment by martin9700** [comment]
Right?! As soon as I read about it I switched all my modules to use that!
