### ISSUE TITLE
Investigate adding refresh token functionality to Invoke-vRARestMethod

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#236]
Part of the output from ```Connect-vRAServer``` is a refresh token. Investigate adding this as functionality to Invoke-vRARestMethod so that then token is refreshed on each API call.

**Comment by Stevio54** [comment]
Not a bad idea, but I think the default in vRA for the refresh token is like 24 hours or something, so may not be needed too often.

**Comment by Stevio54** [comment]
So, I dug into the Identity Manager source code and found that the refresh token by default does not expire for 90 days. So this may be a non-issue at this point.

**Comment by Stevio54** [comment]
further digging, I found this: [https://docs.vmware.com/en/VMware-Workspace-ONE-Access/3.3/idm-administrator/GUID-B2F274FB-4598-4CF1-A9A4-3360E0762DBA.html](https://docs.vmware.com/en/VMware-Workspace-ONE-Access/3.3/idm-administrator/GUID-B2F274FB-4598-4CF1-A9A4-3360E0762DBA.html)

**Comment by Stevio54** [comment]
Refresh = 90 days
Idle token time = 10 Days
Access token though is only 3 hours, so I scratch my last comment, may be good to update the Access Token. However, review my latest pull request around the Connect-vRAServer to make sure and complete the "2-step" login process each time.
