### ISSUE TITLE
FEATURE REQUEST: Network profile support

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#24]
Feature request to support New-vRANetworkProfile

**Comment by chelnak** [comment]
Moved milestone

**Comment by jdmalone** [comment]
What is the status of adding support for Network Profiles?

**Comment by chelnak** [comment]
Hi @jdmalone - sorry its taken so long to reply. 

Support for network profiles is still in the works.. I stopped development on it because I kept finding bugs when trying to set ip ranges. Using the methods in the iaas-proxy-provider api would wipe out fields in the IaaS DB causing things to break.

I did a write up about the bug a while back.. which i actually discovered when doing some vRO work-> https://www.helloitscraig.co.uk/2015/10/issues-with-the-network-profile-api-iaas-proxy-providernetworkprofiles.html

The problem still existed when I came to add support for PowervRA, so decided it wasn't safe to move forward.

There is a branch for it if you wish to check it out (at your own risk of course)

Will update this thread with more information when I have it.

Thanks
Craig
:-)

**Comment by chelnak** [comment]
Update and furthere explanation of bug:

When you create a network profile with IPRanges the profile gets created successfully along with the ranges. However, the addresses for the range are NOT associated with the range in the IaaS DB. They are present but the IPRangeId field is null. This causes really strange behavior int the UI and consiquently when you do a GET on the new range no IP addresses are returned.

This bug appears to exist in versions 6x and 7. Tests on 7.1 show that the bug is no longer present.

So hopefully the next release (1.4.0) will include network profile support but New/Set operations will only be supported for version 7.1 and above.

**Comment by chelnak** [comment]
PR #74 submitted

**Comment by jonathanmedd** [comment]
Woo - this one can now be closed :-)
