### ISSUE TITLE
Issue: Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by spidey323** [jakkulabs/PowervRA#243]
Steps to reproduce
------------------
[Net.ServicePointManager]::SecurityProtocol = "Tls, Tls11, Tls12, Ssl3"
Connect-VRaServer -server test.com -Username "me" -password $pw -IgnoreCertRequirements

Expected behavior
-----------------
connect without errors

Actual behavior
---------------
Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.

Environment data
----------------
vra8.2 with PvRA 4.1

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
> $vRAConnection
n/a
```

**Comment by jonathanmedd** [comment]
Thanks for reporting. We're already aware of one issue with `Connect-vRAServer` and vRA 8.2 - will see if this one is related /cc @Stevio54

**Comment by Stevio54** [comment]
Hello, I have been unable to recreate this issue in three different environments. It seems the issue may be in how your environment is set?

**Comment by Stevio54** [comment]
A colleague @mpuckett159 suggested checking this: [https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel), as this may be an issue in how Powershell is handling the protocols, you may need to change the order or try some of the other soltinos here.
