### ISSUE TITLE
Allow Invoke-vRARestMethod to take PATCH Method (v4+) 

### ISSUE THREAD

**Issue by tocano33** [jakkulabs/PowervRA#244]
I'm only really looking at 4.x, but is there a reason why Invoke-vRARestMethod does not accept PATCH as a method? 

Since there are numerous endpoints in the vRA REST API that utilize the PATCH method, it would seem reasonable to include it - especially since, from what I can gather from looking at the code for this function, it simply forwards it to Invoke-WebRequest/Invoke-RestMethod, both of which do accept PATCH as a valid method.

Thanks.

**Comment by jonathanmedd** [comment]
Thanks for the suggestion, has been implemented.
