### ISSUE TITLE
Unable to Connect-vRAServer with a domain account

### ISSUE THREAD

**Issue by MadMiki88** [jakkulabs/PowervRA#251]
Steps to reproduce
------------------
Connect-vRAServer -Server vra-accp.hostname.domain -Username username@domain -Password $SecuredPassword

Expected behavior
-----------------
Connecting to the 

Actual behavior
---------------

Connect-vRAServer : Is it possible that your environment has userPrincipalName set as the Username attribute? If so, please make sure to include the parameter UserAttribute and set it to either UPN or userPrincipalName (e.g. -UserAttribute UPN)
 {"timestamp":1612275381730,"type":"CLIENT_ERROR","status":"400 BAD_REQUEST","error":"Bad Request","serverMessage":"REST error received: {\n \"error\": \"invalid_grant\",\n \"error_description\": \"Invalid username or password\"\n}, status code: 400 BAD_REQUEST"}

Tried to used -UserAttribute UPN, SAM, didn't work.

Environment data
----------------

We have multiple Multi-tenancy on vIDM. We are able to connect with a local account with this command. But not with a domain account. ANd with the same domain account, we able to connect in the Web UI.

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> $vRAConnection

```

**Comment by MadMiki88** [comment]
When I'm using the  with the local admin account, I have this information after the connection:

APIVersion: 2019-01-05
SignedCertificates: True
SslProtocol: Default

**Comment by jonathanmedd** [comment]
Could you confirm which version of vRA you are using?

**Comment by MadMiki88** [comment]
I'm using Version 8.2.0.13070 (17151459)

**Comment by MadMiki88** [comment]
Found out that the that the API authentification thought out IDM was the problem. Solved it with the support... !

**Comment by jonathanmedd** [comment]
Glad it worked out, thanks for letting us know
