### ISSUE TITLE
Prepare dev branch for reservation-service

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#28]
Following the merge of the reservation-service branch, we need to complete the following tasks:

- Update docs in dev branch
- Update Module manifest to include the new functions

@jonathanmedd Am assigning this to you just for awareness just in case i go AWOL ;-)

**Comment by jonathanmedd** [comment]
@chelnak Remind me what I would need to do to update the docs in the dev branch?

**Comment by chelnak** [comment]
@jonathanmedd Maybe it's something I can write up and stick on the wiki... It needs a bit of polish ;-). For now though if you do the manifest I can do the docs.

**Comment by chelnak** [comment]
Done
