### ISSUE TITLE
The Set-vRAReservation [-AlertFrequencyReminder] is not work.

### ISSUE THREAD

**Issue by dteixeirars** [jakkulabs/PowervRA#44]
Error in variable name "AlertFrequencyReminder" in function "Set-vRAReservation".

**Comment by chelnak** [comment]
Good spot!

The parameter should actually be **AlertReminderFrequency** to match New-vRAReservation

This has also been updated to reflect the change:


```
            if ($PSBoundParameters.ContainsKey("AlertReminderFrequency")){

                Write-Verbose "Updating Alert Policy Reminder Frequency: $($Reservation.alertPolicy.frequencyReminder) >> $($AlertReminderFrequency)"

                $Reservation.alertPolicy.frequencyReminder = $AlertReminderFrequency
}

```

:-)

**Comment by chelnak** [comment]
@dteixeirars Issue fixed/tested and pushed to the development branch.

It will be incorporated in the next release. Thanks for pointing it out!
