### ISSUE TITLE
Add Pipeline support to Export-vRAContentPackage

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#50]
Add Pipeline support to Export-vRAContentPackage. Not sure why it is not there, looks straightforward to implement.

Should be able to do:

Get-vRAContentPackage -Name ContentPackage01 | Export-vRAContentPackage -File C:\Packages\ContentPackage01.zip

**Comment by chelnak** [comment]
@jonathanmedd I've completed this as I had a bit of spare time. Just needs your review.

**Comment by jonathanmedd** [comment]
Done
