### ISSUE TITLE
Function folders

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#51]
@jonathanmedd Working on the build scripts and wondering if this would make more sense:

Functions\Private
Functions\Public

Rather than:
Functions
Functions\Private Functions

What do you think

**Comment by jonathanmedd** [comment]
Yep, I think that makes sense with the introduction of what we have done for Private. 

What do you think about PowervRO where we already have folders. If we added a Private folder at some point, should we then move all existing folders into Function\Public?

**Comment by chelnak** [comment]
Yes agreed. We should mirror the layout as Im sure we will use private
functions in PowervRO at some point in the future. I also found a bug in
the build script that i will need to fix in PowervRO.

I have the layout I mentioned above ready to commit and push. I'll do it
asap.

Cheers

**Comment by jonathanmedd** [comment]
OK, cool

**Comment by chelnak** [comment]
Implemented and pushed to development branch
