### ISSUE TITLE
 New-vRAReservation fail with error 10101 Illegal GUID format null

### ISSUE THREAD

**Issue by saveriosalatino** [jakkulabs/PowervRA#65]
New vRAReservation fail with error 10101 "Illegal GUID Fromat null".
Info and example:

Get-vRAVersion

BuildNumber        : 3621464
BuildDate          : 2016-03-04 06:35
ProductVersion     : 7.0.1-SNAPSHOT
APIVersion         : 7.0
ProductBuildNumber : 7.0.1-SNAPSHOT-3621464

$ComputeResource = Get-vRAReservationComputeResource -Type vSphere -Name "CLUSTER (abc)"

$NetworkDefinitionArray = @()
$Network1 = New-vRAReservationNetworkDefinition -Type vSphere -ComputeResourceId $ComputeResource.Id -NetworkPath "PG_CLCUSTER-IP"
$NetworkDefinitionArray += $Network1

$StorageDefinitionArray = @()
$Storage1 = New-vRAReservationStorageDefinition -Type vSphere -ComputeResourceId $ComputeResource.Id -Path "DS_LUN_CLUSTER" -ReservedSizeGB 3200 -Priority 0
$StorageDefinitionArray += $Storage1

# --- Set the parameters and create the reservation
$Param = @{

    Type = "vSphere"
    Name = "XXXXXXX"
    Tenant = "tenant"
    BusinessGroup = "XXXXX"
    Priority = 0
    ComputeResourceId = $ComputeResource.Id
    MemoryGB = 18
    Storage = $StorageDefinitionArray
    Network = $NetworkDefinitionArray
    EnableAlerts = $false

}

New-vRAReservation @Param -Verbose

New-vRAReservation @Param -Verbose
VERBOSE: Preparing reservation payload
VERBOSE: Reservation name is RES_CL01_MIBER_AUPP
VERBOSE: ReservationTypeId for vSphere is Infrastructure.Reservation.Virtual.vSphere
VERBOSE: Tenant is nfvi-automation
VERBOSE: BusinessGroupId for XXXXX is c71c2d5f-f165-4672-9921-e0de467d6751
VERBOSE: ReservationPolicyId for  is null
VERBOSE: Priority is 0
VERBOSE: Alerts enabled: false
VERBOSE: Email business group manager: false
VERBOSE: Adding extensionData for type vSphere
VERBOSE: Found compute resource XXXXXXXXX with id c83e77ca-9305-4418-b4cd-d887593c7581
VERBOSE: Setting machine quota to 0
VERBOSE: Setting reservation networks
VERBOSE: Setting reservation storage
VERBOSE: Setting reservation memory
VERBOSE: Performing the operation "New-vRAReservation" on target "XXXXXXXXXX".
VERBOSE: Preparing POST to /reservation-service/api/reservations
Invoke-RestMethod : {"errors":[{"code":10101,"message":"Invalid argument.","systemMessage":"Illegal GUID format null","moreInfoUrl":null}]}
At C:\Program Files\WindowsPowerShell\Modules\PowervRA\1.3.1\Functions\Public\Invoke-vRARestMethod.psm1:117 char:25
+ ... $Response = Invoke-RestMethod -Method $Method -Headers $Headers -Uri  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by chelnak** [comment]
@saveriosalatino Thanks for logging the bug. I'll take a look at this later tonight and get back to you.

As a test. Would you kindly try re running your command but this time add a reservation policy?

Thanks
Craig

**Comment by chelnak** [comment]
@saveriosalatino PR submitted for review. Thanks for letting us know about the bug :-)

**Comment by saveriosalatino** [comment]
Hi @chelnak , the cmdlet work using a reservation policy.

**Comment by chelnak** [comment]
Release 1.3.2 with fix for this issue is inbound shortly.

**Comment by chelnak** [comment]
Resolved in v1.3.2 :-)

@saveriosalatino Please update your module. :-)
