### ISSUE TITLE
Add PSScriptAnalyzerSettings.psd1 file to prevent PS Gallery warnings

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#70]
We currently do this to avoid generating an error for username / password with ScriptAnalyzer

    $Exclusions = "PSAvoidUsingUserNameAndPassWordParams"

    $Results = Invoke-ScriptAnalyzer -Path $ModuleDirectory -Severity Error -ExcludeRule $Exclusions -Recurse -Verbose:$VerbosePreference

However, we still get the error when the tests are run in the PS Gallery. Adding a Add PSScriptAnalyzerSettings.psd1 will stop this:

https://github.com/PowerShell/psscriptanalyzer#settings-support-in-scriptanalyzer

**Comment by chelnak** [comment]
Tested and merged with some additions

- PSScriptAnalyzerSettings now lives in the root directory - As per the Plaster module
- Moved psake.build.ps1 to the root directory and renamed to build.psake.ps1 - As per the Plaster module
- Created build.settings.ps1 and migrated some settings from build.ps1 to this

In reality a couple of items should have been done in their own branch however it is all non module impacting work

**Comment by jonathanmedd** [comment]
Nice one
