### ISSUE TITLE
Update the Module Manifest to better support the PowerShell Gallery

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#72]
Add the following section:

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/jakkulabs/PowervRA/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/jakkulabs/PowervRA'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

**Comment by chelnak** [comment]
@jonathanmedd Have just pushed changes that inlcude improved build script and this PSData section. See latest module manifest.

**Comment by jonathanmedd** [comment]
Nice one!
