### ISSUE TITLE
xRequires not evaluating versions

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#73]
It appears that xRequires is no longer evaluating some APIVersions as expected.

When passing a single digit it appears to work however when you pass a value with a decimal the test fails.

I think this is because the parameter type is an Int and values such as 7.1 are doubles...

Example:

APIVersion = 7.0
RequiredVersion = 7.1

xRequires -Version 7.1 will PASS.

Solution:

- Change the parameter type back to [String]
- Cast $Global:vRAConnection.APIVersion as [version]
- Cast $Version as [Version]

Further explanation can be found [http://www.powershellmagazine.com/2014/01/03/pstip-validating-version-numbers-without-regex/](here).

**Comment by chelnak** [comment]
Commit made - Requires testing

**Comment by jonathanmedd** [comment]
Nice work 👍
