### ISSUE TITLE
Add support for LocalScopeForActions to Set-vRAEntitlement / New-vRAEntitlement

### ISSUE THREAD

**Issue by chelnak** [jakkulabs/PowervRA#76]
Add support for LocalScopeForActions to Set-vRAEntitlement / New-vRAEntitlement.

This would mean that the function becomes unsupported for 6x but is a useful feature to have

**Comment by jonathanmedd** [comment]
Perhaps we could just throw the function if that parameter is used against a 6.x and say it is not supported?
