### ISSUE TITLE
Get-vRAUserPrincipal

### ISSUE THREAD

**Issue by thecloudxpert** [jakkulabs/PowervRA#80]
is it possible to show whether or not the user is a local user or a replicated user from an identity source? just like in the Get-vRAGroupPrincipal shows CUSTOM or SSO.

**Comment by chelnak** [comment]
The LocalUsersOnly switch will return local users but off the top of my head I can't remember if the API returns a type attribute.. if it did I'm sure we would have added it to the PSCustomObject that is returned.

Will look in to it and let you know what we find!

**Comment by chelnak** [comment]
Doesn't look like this information is provided by the groups api :-(
