### ISSUE TITLE
Get-vRAGroupPrincipal

### ISSUE THREAD

**Issue by thecloudxpert** [jakkulabs/PowervRA#81]
is it possible to show/list what users/groups are included in the Groups as property or maybe another function like Get-vRAGroupPrincipleMembers? I can see that being helpful to identify if there are synch issues between vIDM and AD - if a new user/group added to AD but isn't showing in vRA yet. 

so you could do something like:

Get-vRAPrinciple -Name "CustGroup1" | Get-vRAGroupPrincpleMembers

**Comment by chelnak** [comment]
**Get-vRAUserPrincipalGroupMembership** will be in release 2.2.0 👍
