### ISSUE TITLE
New feature modify vRa All services icons

### ISSUE THREAD

**Issue by laurentmas** [jakkulabs/PowervRA#87]
Hi,

Since vRa 7.1 we can update All services icons using vRa api.

It will be nice if you can add this feature on PowervRa.

Here the description how to do it : http://pubs.vmware.com/vrealize-automation-71/index.jsp?topic=%2Fcom.vmware.vrealize.automation.doc%2FGUID-EEE2C14E-6C1B-4113-9001-6B2B6DB66C48.html&resultof=%22Modify%22%20%22modifi%22%20%22all%22%20%22services%22%20%22servic%22%20%22icon%22%20

Regards

**Comment by chelnak** [comment]
Great idea. I can see this being part of something like Set-vRAServiceIcon.

We'll take a look.

**Comment by jonathanmedd** [comment]
I'll be doing the following

New functions: Get-vRAServiceIcon, Import-vRAServiceIcon, Export-vRAServiceIcon, Remove-vRAServiceIcon
Updated functions: Set-vRAService and New-vRAService with IconId parameter

**Comment by jonathanmedd** [comment]
Closed via the above pull request
