### ISSUE TITLE
Error: The maximum depth allowed for serialization is 100

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#96]
In WMF 5.1 / PowerShell 6 the maximum depth for ConvertTo-JSON appears to have been restricted to 100. The following functions need to be updated, since they are producing these errors:

Add Storage to named Reservation Reservation100 31.48s
   The maximum depth allowed for serialization is 100.
   at line: 94 in /Users/jon_medd/.local/share/powershell/Modules/PowervRA/Functions/Public/Add-vRAReservationStorage.ps1
 [-] Add Network to named Reservation Reservation100 37.83s
   The maximum depth allowed for serialization is 100.
   at line: 96 in /Users/jon_medd/.local/share/powershell/Modules/PowervRA/Functions/Public/Add-vRAReservationNetwork.ps1

[-] Update named Reservation Reservation100 18.97s
   The maximum depth allowed for serialization is 100.
   at line: 575 in /Users/jon_medd/.local/share/powershell/Modules/PowervRA/Functions/Public/Set-vRAReservation.ps1

**Comment by chelnak** [comment]
Nice spot. I've cleared up a few of these previously. Picked them up when
doing the catlalog service re work on my win10 machine.

Where should I fix them? In the core branch or in Dev once we have merged?
Want to try and minimise conflicts!

**Comment by jonathanmedd** [comment]
I already fixed them here. Figured it was OK to do it here since it was part of making it ready for PS Core?

**Comment by chelnak** [comment]
Ok good stuff. 🥇

**Comment by jonathanmedd** [comment]
Fixed, with above mentioned commits
