### ISSUE TITLE
Get-vRAContentData fails on PowerShell Core

### ISSUE THREAD

**Issue by jonathanmedd** [jakkulabs/PowervRA#97]
$ContentData = Get-vRAContent -Id $TestContent.Id | Get-vRAContentData

Invoke-RestMethod : Unexpected character encountered while parsing value: i. Path '', line 0, position 0.
At /Users/jon_medd/.local/share/powershell/Modules/PowervRA/Functions/Public/Invoke-vRARestMethod.ps1:125 char:21
+         $Response = Invoke-RestMethod @Params
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], JsonReaderException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonReaderException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by chelnak** [comment]
Just as we thought:

![image](https://cloud.githubusercontent.com/assets/3777574/21729927/27a67952-d445-11e6-9be9-2a0cbc1c33bb.png)

You can see it's ignoring the content type of the response.. also found this issue which confirms the issue:

https://github.com/PowerShell/PowerShell/issues/2245

**Comment by chelnak** [comment]
A quick test with Invoke-WebRequest seems to be successful...

```
 (Invoke-WebRequest -Uri  https://httpbin.org/robots.txt).content
```

**Comment by chelnak** [comment]
I've implemented a check to fail this function if it is executed in Core:

```
        if ($PSVersionTable.PSEdition -eq "core") {

            throw "This function does not support PowerShell Core Edition"

        }

```

Have tested in 4.0, 5.1 + 6 alpha 14 and results appear to be as expected.

I noticed that Nick Bradford (PowerNSX) had also commented on the same issue back in November.  It appears that he has a work around but in my opinion it is too complicated to implement just for the benefit of one function. If the user want's to view data they can create a package and export it to see the content.

What are your views @jonathanmedd ?

**Comment by jonathanmedd** [comment]
Good job! Yes, completely agree with the solution for now. I think maybe we just leave this issue open as a reminder to track the PowerShell bug and hopefully can remove this change at some point?

**Comment by chelnak** [comment]
Sounds good!

**Comment by jonathanmedd** [comment]
The issue preventing this from working has been resolved in PowerShell Alpha 15 - https://github.com/PowerShell/PowerShell/issues/2245. I have tested this and all is now good for Get-vRAContentData

**Comment by jonathanmedd** [comment]
We will of course have to raise the support level for PowervRA in the next release to be PowerShell Alpha 15
